using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class Names {
    public static string[] Warrior = { "Aseir", "Haseid", "Kheed", "Zasheir", "Fodel", "Glar", "Grigor", "Igan", "Ivor", "Kosef", "Mival", "Pavel", "Sergor", "Darvin", "Dorn", "Evendur", "Gorstag", "Helm", "Morn", "Randal", "Stedd", "Ander", "Blath", "Bran", "Frath", "Geth", "Lander", "Luth", "Malcer", "Stor", "Taman", "Bareris", "Kethoth", "Mumed", "Urhur", "Borivik", "Faurgar", "Jandar", "Kanithar", "Madislak", "Ralmevik", "Shaumar", "Vladislak", "Chen", "Chi", "Fai", "Jiang", "Jun", "Lian", "Long", "Meng", "Shan", "Wen", "Anton", "Diero", "Marcon", "Pieron", "Rimardo", "Romero", "Salazar", "Umbero" };
    public static string[] Rogue = { "Aiden", "Alaric", "Aleister", "Ambrose", "Ansel", "Archibald", "Arman", "Art", "Artemus", "Asa", "Asher", "Augustus", "Axton", "Bane", "Bartholomew", "Benedict", "Blaise", "Bowen", "Braden", "Braeden", "Braiden", "Branden", "Brendan", "Brock", "Broden", "Brody", "Caden", "Cael", "Cage", "Calder", "Caius", "Camden", "Casimir", "Caspian", "Cassius", "Chael", "Chance", "Chandler", "Chase", "Cillian", "Clay", "Clayton", "Cletus", "Conrad", "Cullen", "Dagan", "Damien", "Dash", "Declan", "Dorian", "Duncan", "Dustyn", "Dwyer", "Eamon", "Easton", "Egan", "Eli", "Emmett", "Everett", "Ezra", "Finn", "Finnian", "Fletcher", "Fraser", "Gatlin", "Graham", "Greyson", "Gunnar", "Haden", "Hank", "Harlan", "Harrison", "Hayden", "Heath", "Hendrix", "Holden", "Houston", "Howard", "Hudson", "Ian", "Isaac", "Jackson", "Jaden", "Jagger", "Jakob", "Jameson", "Jaxon", "Jett", "Joaquin", "Jonah", "Josiah", "Jules", "Julian", "Kellan", "Kellen", "Knox", "Knoxville", "Kyler", "Landon", "Larkin", "Lazarus", "Lee", "Leland", "Lennon", "Lion", "Lucian", "Madden", "Maddox", "Magnus", "Malcolm", "Maximus", "Maxon", "Miles", "Milo", "Monty", "Nash", "Nathanael", "Neill", "Nile", "Odin", "Orlando", "Owen", "Patrick", "Paxton", "Phoenix", "Quill", "Quillon", "Quinn", "Ragnar", "Raleigh", "Rowan", "Rowen", "Sawyer", "Seamus", "Sebastian", "Soren", "Sterling", "Thatcher", "Thayer", "Thelonious", "Thor", "Thorne", "Tobias", "Tucker", "Turner", "Tybalt", "Tye", "Tyson", "Vaughn", "Viggo", "Viktor", "Wade", "Walker", "Waylon", "Wilder", "Wiley", "Winston", "Zane", "Zion" };
    public static string[] Wizard = { "Alaric", "Aldwyn", "Aneirin", "Archibald", "Artemus", "Barrett", "Benedict", "Blythe", "Braeden", "Brunswick", "Cadoc", "Cai", "Calder", "Casimir", "Caspian", "Cassius", "Cornelius", "Dagonet", "Desmond", "Dorian", "Edmund", "Everett", "Fabian", "Falken", "Fenton", "Ferris", "Finley", "Fletcher", "Galen", "Gannon", "Gavin", "Godric", "Griffin", "Gryffin", "Gunther", "Gwendolyn", "Hadley", "Hank", "Harper", "Hector", "Heinrich", "Howard", "Hugo", "Ingvar", "Ioan", "Isaac", "Isadore", "Jagger", "Jasper", "Jethro", "Josiah", "Julien", "Kael", "Kai", "Knox", "Lachlan", "Landon", "Laurent", "Lawson", "Leif", "Lestrange", "Lucien", "Magnus", "Malachi", "Mercer", "Miles", "Montgomery", "Mordechai", "Morgan", "Murdoch", "Murphy", "Myles", "Neal", "Nicholas", "Owen", "Phelan", "Quill", "Rafferty", "Rowan", "Ryder", "Sawyer", "Silas", "Sirius", "Solomon", "Stratford", "Thaddeus", "Thelonious", "Tobias", "Tucker", "Vance", "Viktor", "Wesley", "Westley", "Wilfred", "Willow", "Winston", "Zane", "Zion", "Zyrah" };
    public static string[] RogueNick = {"Bandit",
"Cutpurse",
"Prowler",
"Burglar",
"Filcher",
"Fence",
"Pickpocket",
"Purloiner",
"Thief",
"Swindler",
"Sharper",
"Con Artist",
"Grifter",
"Hustler",
"Operator",
"Wheeler Dealer",
"Trickster",
"Deceiver",
"Double-crosser",
"Snake in the Grass",
"Two-faced",
"Double Dealer",
"Judas",
"Quisling",
"Turncoat",
"Informer",
"Stool Pigeon",
"Rat",
"Sneak",
"Skulker",
"Slinker",
"Slitherer",
"Fox",
"Vixen",
"Slyboots",
"Sly dog",
"Sly old fox",
"Wily old fox",
"Artful dodger",
"Old hand",
"Pro",
"Veteran",
"Expert",
"Seasoned",
"Adept",
"Master",
"Grandmaster",
"Guru",
"Sage",
"Sensei",
"Teacher",
"Instructor",
"Trainer",
"Pupil",
"Student",
"Neophyte",
"Apprentice",
"Tyro",
"Greenhorn",
"Novice",
"Rookie",
"Would-be",
"Amateur",
"Wannabe",
"Poseur",
"Pretender",
"Charlatan",
"Impostor",
"Mountebank",
"Fraud",
"Fake",
"Phony",
"Sham",
"Confidence trickster",
"Con man",
"Con woman",
"Flim-flam artist",
"Gilder",
"Gimcrack",
"Huckster",
"Quack",
"Swindler",
"Sharper",
"Trickster",
"Scoundrel",
"Knave",
"Rogue",
"Villain",
"Blackguard",
"Scamp",
"Rake",
"Gallant",
"Roué",
"Debauchee",
"Libertine",
"Lecher",
"Lothario",
"Philanderer",
"Womanizer" };
    public static string[] Wizardnick = { "The Wise One", "The Sage", "The Conjurer", "The Magus", "The Necromancer", "The Warlock", "The Enchantress", "The Sorceress", "The Wizard of Oz", "Merlin", "The Great Wizard", "Gandalf", "The White Wizard", "The Black Wizard", "The Grey Wizard", "The Blue Wizard", "The Red Wizard", "The Green Wizard", "The Brown Wizard", "The Yellow Wizard", "The Orange Wizard", "The Purple Wizard", "The Gold Wizard", "The Silver Wizard", "The Platinum Wizard", "The Diamond Wizard", "The Crystal Wizard", "The Glass Wizard", "The Smoke Wizard", "The Fire Wizard", "The Ash Wizard", "The Storm Wizard", "The Lightning Wizard", "The Wind Wizard", "The Frost Wizard", "The Ice Wizard", "The Snow Wizard", "The Wave Wizard", "The Ocean Wizard", "The Swamp Wizard", "The Tree Wizard", "The Flower Wizard", "The Sun Wizard", "The Moon Wizard", "The Star Wizard", "The Phoenix Wizard", "The Dragon Wizard", "The Unicorn Wizard", "The Pegasus Wizard", "The Minotaur Wizard", "The Sphinx Wizard", "The Griffin Wizard", "The centaur Wizard", "The Fairy Wizard", "The Elf Wizard", "The Dwarf Wizard", "The Orc Wizard", "The Goblin Wizard", "The Troll Wizard", "The Giant Wizard", "The Demon Wizard", "The Devil Wizard", "The Angel Wizard", "The Saint Wizard", "The Priest Wizard", "The Nun Wizard", "The Rabbi Wizard", "The Imam Wizard", "The Shaman Wizard", "The Medicine Man Wizard", "The Witch Doctor Wizard", "The Voodoo Wizard", "The Hoodoo Wizard", "The Santeria Wizard", "The Kabbalah Wizard", "The Druid Wizard", "The Pagan Wizard", "The Wiccan Wizard", "The Summoner Wizard", "The Necromancer Wizard", "The Elemental Wizard", "The Air Wizard", "The Water Wizard", "The Earth Wizard", "The Fire Wizard", "The Aether Wizard", "The Chronomancer Wizard", "The Psychomancer Wizard", "The Dimensional Wizard", "The Time Wizard", "The Space Wizard", "The Reality Wizard", "The Illusion Wizard", "The Dream Wizard", "The Nightmare Wizard", "The Death Wizard", "The Life Wizard" };
    public static string[] Warriornick = {"Mighty",
"Fearlesss",
"Courageouss",
"Daring",
"Intrepid",
"Bold",
"Daring",
"Valiant",
"Fearless",
"Gallant",
"Great",
"Heroic",
"Intrepid",
"Noble",
"Brave",
"Courageous",
"Valorous",
"Intrepid",
"Heroic",
"Audacious",
"Dauntless",
"Determined",
"Resolute",
"Tenacious",
"Relentless",
"Unstoppable",
"Indomitable",
"Unyielding",
"Unshakeable",
"Unbreakable",
"Indestructible",
"Unstoppable",
"Unbeatable",
"Unconquerable",
"Supreme",
"All-powerful",
"Almighty",
"Master",
"Great",
"Ultimate" };

}
